version: '3.8'

services:
  db:
    container_name: db
    image: postgres:12
    environment:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_DB: ${POSTGRES_DB}
    ports:
        - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

  php-fpm:
    container_name: php-fpm
    build:
      context: ./php-fpm
    depends_on:
      - db
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable&charset=utf8
      - MAILER_DSN=smtp://.kinza@yandex.ru:dsf2fsdf3FWdsdDSF2234@smtp.yandex.ru:465?encryption=ssl&auth_mode=login
      - MESSENGER_TRANSPORT_DSN=amqp://guest:guest@rabbit:5672/%2f/messages
      - XDEBUG_CONFIG=client_host=host.docker.internal client_port=9003
    volumes:
      - sync-rsync:/var/www
      - ./php-fpm/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini

  rabbit:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/data

  supervisor:
    build:
      context: ./supervisor
    depends_on:
      - db
      - rabbit
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable&charset=utf8
      - MAILER_DSN=smtp://vlad.kinza@yandex.ru:dsf2fsdf3FWdsdDSF2234@smtp.yandex.ru:465?encryption=ssl&auth_mode=login
      - MESSENGER_TRANSPORT_DSN=amqp://guest:guest@rabbit:5672/%2f/messages
    volumes:
      - sync-rsync:/var/www
      - ./logs/supervisor:/var/log/supervisor
      - ./supervisor/supervisord.conf:/etc/supervisor/supervisord.conf:ro
      - ./supervisor/worker.conf:/etc/supervisor/conf.d/worker.conf:ro

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    volumes:
      - sync-rsync:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./nginx/cert/:/cert
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"

  interact:
    build:
      context: ./node
    tty: true
    depends_on:
      - db
    volumes:
      - sync-node:/var/www
    ports:
      - 8000:8000
      - 8001:8001
      - 8002:8002
      - 8003:8003
    restart: on-failure

volumes:
  sync-rsync:
    external: true
  sync-node:
    external: true
  db:
  rabbitmq_data:
